doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            gare_id_value_object:  App\ImportBoundedContext\Infrastructure\Orm\Types\GareIdMapping
            connexion_id_value_object:  App\ImportBoundedContext\Infrastructure\Orm\Types\ConnexionIdMapping
            ligne_id_value_object:  App\ImportBoundedContext\Infrastructure\Orm\Types\LigneIdMapping
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ImportBoundedContext:
                type: xml
                dir: '%kernel.project_dir%/src/ImportBoundedContext/Infrastructure/Orm/Mapping'
                prefix: 'App\ImportBoundedContext\Domain\Model'
#             TestEntity:
#                 is_bundle: false
#                 dir: '%kernel.project_dir%/src/Shared/Orm/Entity'
#                 prefix: 'App\Shared\Orm\Entity'
#                 alias: App
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
