version: '3'

services:
  api:
    image: webdevops/php-apache:8.2
    container_name: metro
    ports:
      - "8080:80"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
      - WEB_DOCUMENT_INDEX=index.php
      - VIRTUAL_HOST=metro.local
    expose:
      - 80
    volumes:
      - ./:/var/www
      - tmp:/tmp
  mysql:
    image: mysql:8.1
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  mosquitto:
    restart: on-failure
    image: eclipse-mosquitto:2.0.17
    container_name: mosquitto
    expose:
      - 1883
    ports:
      - "1883:1883"
    volumes:
      - ./Resources/config_mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./Resources/config_mosquitto/.mosquitto:/mosquitto/config/.mosquitto:r

volumes:
  mysql_data:
  tmp:
