<?php

declare(strict_types=1);

namespace App\ImportBoundedContext\Domain\Model\Gare;

use App\Shared\Domain\Model\ArrayObject;
use App\Shared\Exception\InvalidCollectionParameterException;

/**
 * @extends ArrayObject<Gare>
 */
class GareArrayObject extends ArrayObject
{
    /** @var string */
    protected string $collectionClassType = Gare::class;

    /**
     * @param Gare $value
     * @return void
     * @throws InvalidCollectionParameterException
     */
    public function append(mixed $value): void
    {
        parent::append($value); // TODO: Change the autogenerated stub
    }
}
